# This produces the image in the simplest way, but the latest version of SISTR is not always available via
# this mechanism.
# An alternative to this approach is to use miniconda, but SISTR had not been updated to v1.1.2.
FROM ummidock/sistr_cmd:1.0.2
FROM staphb/sistr:1.1.1

COPY . /opt/pathogenwatch

CMD [ "sh", "/opt/pathogenwatch/index.sh" ]