# Dockerfile for running single scheme images that ignore the input taxon ID

ARG BASE
FROM registry.gitlab.com/cgps/cgps-mlst/${BASE}

ARG TASK
ENV PW_TASK ${TASK:-mlst}

RUN apt update && \
    apt install -y --no-install-recommends curl && \
    rm -rf /var/lib/apt/lists

COPY formatter.js /pathogenwatch/formatter.js
COPY entrypoint.sh /pathogenwatch/entrypoint.sh

# Test for singularity
#RUN chmod -R o+rX /usr/local/mlst/index_dir

ARG ORGANISM_ID
ENV ORGANISM_TAXID=$ORGANISM_ID
ENV SPECIES_TAXID=$ORGANISM_ID
ENV GENUS_TAXID=$ORGANISM_ID

ENTRYPOINT []
CMD [ "/pathogenwatch/entrypoint.sh" ]
